---
# Overridable values
_patroni_cluster_group: "{{ patroni_cluster_group | default('patroni_cluster') }}"
_patroni_barman_group: "{{ patroni_barman_group | default('patroni_barman') }}"
_patroni_config_hostnames: "{{ patroni_config_hostnames | default(True) }}"

# Hardcoded values
postgresql_service_state: stopped
postgresql_service_masked: true
postgresql_service_enabled: false

_patroni_user: "patroni"
_patroni_group: "patroni"
_patroni_venv: "/opt/patroni/venv"
_patroni_cluster_hosts: "{{ groups[_patroni_cluster_group] }}"
_patroni_barman_hosts: "{{ groups[_patroni_barman_group] }}"
