---
- name: Import facts playbook
  import_playbook: nephelaiio.patroni.facts

- name: Load pagila database
  import_playbook: ./pagila.yml
  vars:
    pagila_db: seed


- name: Crash cluster master
  hosts: _patroni_cluster_master
  become: true
  tasks:
    - name: Stop patroni service
      ansible.builtin.service:
        name: patroni
        state: stopped

    - name: Wait for cluster failover
      ansible.builtin.pause:
        minutes: 1

    - name: Stop patroni service
      ansible.builtin.service:
        name: patroni
        state: started


- name: Load pagila database
  import_playbook: ./pagila.yml
  vars:
    pagila_db: post
