---
- name: Verify package installation
  hosts: patroni_cluster
  any_errors_fatal: true
  vars_files:
    - ../../playbooks/vars/main.yml
  tasks:
    - name: Query client version
      ansible.builtin.command: psql --version
      register: _psql_version

    - name: Check client version
      ansible.builtin.assert:
        that: _version.startswith(_postgresql_release)
      vars:
        _version: "{{ _psql_version.stdout.split(' ')[2] }}"

    - name: Gather service facts
      ansible.builtin.service_facts:

    - name: Check db services
      ansible.builtin.assert:
        that:
          - postgresql_service in services
          - services[postgresql_service].status == 'masked'
          - services[postgresql_service].state == _stopped
      vars:
        _stopped: "{{ (ansible_os_family == 'RedHat') | ternary('inactive', 'stopped') }}"
