---
- name: Set cluster facts
  ansible.builtin.import_playbook: nephelaiio.patroni.facts

- name: Create tables and schemas
  hosts: _patroni_cluster_master
  become: true
  vars_files:
    - ../../../playbooks/vars/main.yml
  tasks:
    - name: Set PostgreSQL facts
      ansible.builtin.include_role:
        name: nephelaiio.patroni.postgresql
        tasks_from: vars.yml

    - name: Set PostgreSQL FDW fact
      ansible.builtin.set_fact:
        _patroni_fdw_databases: "{{ _tables_overwritten }}"
      vars:
        _fdw: "{{ _patroni_cluster_fdw | sort(attribute='remote') }}"
        _tables: "{{ _fdw | map(attribute='tables') | map('dict2items') }}"
        _tables_dict: "{{ _tables | map('nephelaiio.plugins.to_dict', 'tables') }}"
        _tables_overwritten: "{{ _fdw | zip(_tables_dict) | map('combine') }}"

    - name: Create schemas
      community.postgresql.postgresql_schema:
        login_db: "{{ _db }}"
        login_port: "{{ _patroni_haproxy_port_psql_master_local }}"
        name: "{{ _name }}"
      vars:
        _name: "{{ item.schema | default('public') }}"
        _db: "{{ item.source }}"
      loop_control:
        label: "Schema: {{ _name }} - Database: {{ _db }}"
      loop: "{{ _patroni_fdw_databases }}"
      become_user: "{{ _postgresql_user }}"

    - name: Create tables
      community.postgresql.postgresql_table:
        login_db: "{{ _db }}"
        login_port: "{{ _patroni_haproxy_port_psql_master_local }}"
        name: "{{ _name }}"
        columns: "{{ item.1.value.columns }}"
      vars:
        _name: "{{ item.1.key }}"
        _db: "{{ item.0.source }}"
      loop_control:
        label: "Table: {{ _name }} - Database: {{ _db }}"
      loop: "{{ _patroni_fdw_databases | subelements('tables') }}"
      become_user: "{{ _postgresql_user }}"

- name: Run nephelaiio.patroni.fdw playbook
  ansible.builtin.import_playbook: nephelaiio.patroni.fdw

- name: Import verify playbook
  ansible.builtin.import_playbook: ./verify.yml

- name: Override Foreign Data Wrapper data
  hosts: all
  vars_files:
    - ../../../playbooks/vars/main.yml
  tasks:
    - name: Override fdw fact
      ansible.builtin.set_fact:
        patroni_cluster_fdw:
          - source: "{{ patroni_molecule_database }}"
            remote: "{{ patroni_molecule_database }}"
            username: "{{ patroni_molecule_username }}"
            password: "{{ patroni_molecule_password }}"
            tables:
              test:
                columns:
                  - Username character varying(50) NOT NULL
                  - CountryId integer NOT NULL
          - source: "{{ patroni_test_database }}"
            remote: "{{ patroni_test_database }}"
            username: "{{ patroni_molecule_username }}"
            password: "{{ patroni_molecule_password }}"
            tables:
              new:
                columns:
                  - Username character varying(50) NOT NULL
                  - CountryId integer NOT NULL
          - source: "{{ patroni_bla_database }}"
            remote: "{{ patroni_bla_database }}"
            username: "{{ patroni_molecule_username }}"
            password: "{{ patroni_molecule_password }}"
            tables:
              bla:
                columns:
                  - Username character varying(50) NOT NULL
                  - CountryId integer NOT NULL

- name: Run nephelaiio.patroni.fdw playbook
  ansible.builtin.import_playbook: nephelaiio.patroni.fdw

- name: Import verify playbook
  ansible.builtin.import_playbook: ./verify.yml

- name: Override Foreign Data Wrapper data
  hosts: all
  vars_files:
    - ../../../playbooks/vars/main.yml
  tasks:
    - name: Override fdw fact
      ansible.builtin.set_fact:
        patroni_cluster_fdw:
          - source: "{{ patroni_molecule_database }}"
            remote: "{{ patroni_molecule_database }}"
            username: "{{ patroni_molecule_username }}"
            password: "{{ patroni_molecule_password }}"
            tables:
              test:
                columns:
                  - Username character varying(50) NOT NULL
                  - CountryId integer NOT NULL
          - source: "{{ patroni_test_database }}"
            remote: "{{ patroni_test_database }}"
            username: "{{ patroni_molecule_username }}"
            password: "{{ patroni_molecule_password }}"
            tables:
              new:
                columns:
                  - Username character varying(50) NOT NULL
                  - CountryId integer NOT NULL
          - source: "{{ patroni_bla_database }}"
            remote: "{{ patroni_bla_database }}"
            state: absent
            username: "{{ patroni_molecule_username }}"
            password: "{{ patroni_molecule_password }}"
            tables:
              bla:
                columns:
                  - Username character varying(50) NOT NULL
                  - CountryId integer NOT NULL

- name: Run nephelaiio.patroni.fdw playbook
  ansible.builtin.import_playbook: nephelaiio.patroni.fdw

- name: Import verify playbook
  ansible.builtin.import_playbook: ./verify.yml
