---
- name: Gather cluster host facts
  hosts: "{{ _patroni_cluster_hostgroup }}"
  vars_files:
    - main.yml
  tasks:
    - name: Gather host facts
      ansible.builtin.setup:


- name: Deploy Barman
  hosts: "{{ _patroni_barman_hostgroup }}"
  become: true
  any_errors_fatal: true
  vars:
    _barman_ssh_keypair: "~{{ _patroni_barman_user }}/.ssh/id_rsa"
  vars_files:
    - main.yml
  tasks:
    - name: Install Barman package
      ansible.builtin.package:
        name: barman

    - name: Distribute SSH control public keys
      block:
        - name: Create SSH directory
          ansible.builtin.file:
            path: "{{ _barman_ssh_keypair | dirname }}"
            state: directory
            owner: "{{ _patroni_barman_user }}"
            group: "{{ _patroni_barman_group }}"
            mode: 0700

        - name: Create SSH keypair
          community.crypto.openssh_keypair:
            path: "{{ _barman_ssh_keypair }}"
            owner: "{{ _patroni_barman_user }}"
            group: "{{ _patroni_barman_group }}"
          register: _barman_keypair

        - name: Distribute SSH public keys
          ansible.posix.authorized_key:
            comment: "{{ item }}"
            user: postgres
            key: "{{ _barman_keypair.public_key }}"
          loop_control:
            label: "{{ _patroni_barman_user }}@{{ inventory_hostname }} -> {{ item }}"
          loop: "{{ groups[_patroni_cluster_hostgroup] }}"
          delegate_to: "{{ item }}"
