---
- name: Install PostgreSQL cluster members
  hosts: "{{ _postgresql_db_group }}"
  become: true
  vars_files:
    - main.yml
  roles:
    - nephelaiio.postgresql.repo
    - nephelaiio.postgresql
  pre_tasks:
    - name: Create virtualenv
      ansible.builtin.tempfile:
        state: directory
        prefix: .virtualenv
        path: "~"
      register: _virtualenv_tmpdir
      changed_when: false

    - name: Initialize virtualenv
      ansible.builtin.pip:
        name:
          - psycopg2-binary
        virtualenv: "{{ _virtualenv_tmpdir.path }}/venv"
      changed_when: false

    - name: Set ansible interpreter
      vars:
        ansible_python_interpreter: "{{ _virtualenv_tmpdir.path }}/venv/bin/python"

  post_tasks:
    - name: Destroy virtualenv
      ansible.builtin.file:
        path: "{{ _virtualenv_tmpdir.path }}"
        state: absent
      changed_when: false
