---
- name: Deploy Consul
  hosts: "{{ _patroni_consul_hostgroup }}:{{ _patroni_cluster_hostgroup }}"
  become: true
  any_errors_fatal: true
  vars_files:
    - main.yml
  tasks:
    - name: Verify cluster group settings
      ansible.builtin.assert:
        that: (groups[_patroni_consul_hostgroup] | length) in _sizes
        fail_msg: "Patroni Consul group size must be one of [{{ _sizes | join(',') }}], found {{ _size }}"
      vars:
        _size: "{{ groups[_patroni_consul_hostgroup] | length }}"
        _sizes: [3, 5, 7]

    - name: Initialize Consul roles
      ansible.builtin.set_fact:
        consul_node_role: "{{ _role }}"
      vars:
        _role: "{{ 'server' if inventory_hostname in groups[_patroni_consul_hostgroup] else 'client' }}"

    - name: Release Consul package holds
      block:
        - name: Release Consul apt hold
          ansible.builtin.dpkg_selections:
            name: consul
            selection: install
          when: ansible_os_family == "Debian"
          changed_when: false
          ignore_errors: true

        - name: Release Consul yum lock
          community.general.yum_versionlock:
            name: consul
            state: absent
          when: ansible_os_family == "RedHat"
          changed_when: false

    - name: Deploy Consul cluster
      ansible.builtin.include_role:
        name: nephelaiio.patroni.consul
      vars:
        consul_version: "{{ _patroni_release_consul }}"
        consul_bootstrap_expect: true
        consul_bootstrap_expect_value: "{{ groups[_patroni_consul_hostgroup] | length }}"
        consul_group_name: "{{ _patroni_consul_hostgroup }}"
        consul_datacenter: "{{ _patroni_consul_datacenter | regex_replace('[.]', '_') }}"
        consul_encrypt_enable: false
        consul_os_repo_prerequisites: []
        consul_bin_path: "{{ (consul_install_from_repo | default(False) | bool) | ternary('/usr/bin', '/usr/local/bin') }}"
        consul_install_from_repo: true
        consul_install_dependencies: false
        consul_os_packages:
          - unzip
          - acl

    - name: Release Consul package holds
      when: _patroni_release_consul is defined
      block:
        - name: Hold Consul apt package
          ansible.builtin.dpkg_selections:
            name: consul
            selection: hold
          when: ansible_os_family == "Debian"
          changed_when: false

        - name: Lock Consul yum package
          community.general.yum_versionlock:
            name: consul
            state: present
          when: ansible_os_family == "RedHat"
          changed_when: false

    - name: Create Consul backup path
      ansible.builtin.file:
        path: "{{ _patroni_consul_backup_path }}"
        state: directory
        owner: consul
        group: consul
        mode: 0740

    - name: Create Consul backup script
      ansible.builtin.copy:
        dest: "{{ _patroni_consul_backup_bin }}"
        content: |
          cd {{ _patroni_consul_backup_path }}
          consul snapshot save consul.$(date +%Y%m%d-%H%M%S).snap
          stale_backups=$(find ./ -mindepth 1 -maxdepth 1 -type f -mmin {{ _retention }})
          Removing $(echo $stale_backups | wc -l) expired backups
          echo -n $stale_backups | xargs --no-run-if-empty rm
        owner: consul
        group: consul
        mode: 0755
      vars:
        _retention: "{{ _patroni_consul_backup_retention }}"

    - name: Create Consul restore script
      ansible.builtin.copy:
        dest: "{{ _patroni_consul_restore_bin }}"
        content: |
          cd {{ _patroni_consul_backup_path }}
          if [ $# -eq 0 ]; then
            consul snapshot restore
            backup_files=$(find ./ -mindepth 1 -maxdepth 1 -type f -printf "%f\n")
            if [ "$backup_files" != "" ]; then
              echo Please specify one of the following backup files
              echo $backup_files
            fi
          else
            consul snapshot restore $@
          fi
        owner: consul
        group: consul
        mode: 0755

    - name: Create Consul backup MOTD pointers
      ansible.builtin.copy:
        dest: /etc/update-motd.d/99-consul
        content: |
          #!/usr/bin/env bash
          echo run {{ _patroni_consul_backup_bin | basename }} to backup Consul database
          echo run {{ _patroni_consul_restore_bin | basename }} to restore Consul database
          echo
        mode: 0755
      when: ansible_os_family == 'Debian'

    - name: Manage Consul backup cronjob
      ansible.builtin.cron:
        name: consul-snapshot
        job: "{{ _patroni_consul_backup_bin }} 2>&1"
        minute: "{{ _patroni_consul_backup_minutes }}"
        hour: "{{ _patroni_consul_backup_hours }}"
        day: "{{ _patroni_consul_backup_days }}"
