---
- name: Set cluster facts
  ansible.builtin.import_playbook: nephelaiio.patroni.facts
  vars:
    patroni_bootstrap_allow: false


- name: Manage Patroni databases and roles
  hosts: _patroni_cluster_master
  become: true
  vars_files:
    - main.yml
  tasks:
    - name: Manage cluster roles
      ansible.builtin.include_role:
        name: nephelaiio.patroni.postgresql
        tasks_from: roles.yml
      vars:
        postgresql_role_manage: true
        postgresql_roles: "{{ _patroni_cluster_roles }}"

    - name: Manage cluster databases
      ansible.builtin.include_role:
        name: nephelaiio.patroni.postgresql
        tasks_from: databases.yml
      vars:
        postgresql_database_manage: true
        postgresql_databases: "{{ _patroni_cluster_databases }}"
