---
- name: Prepare stack nodes
  ansible.builtin.import_playbook: nephelaiio.patroni.prepare


- name: Deploy proxy nodes
  ansible.builtin.import_playbook: nephelaiio.patroni.haproxy


- name: Deploy Consul cluster
  ansible.builtin.import_playbook: nephelaiio.consul.install
  vars:
    consul_group: "{{ patroni_consul_group | default('patroni_consul') }}:{{ _patroni_cluster_hostgroup }}"
    consul_update_skip_group: "{{ _patroni_update_skip_hostgroup }}:{{ _patroni_cluster_hostgroup }}"


- name: Deploy PostgreSQL cluster
  ansible.builtin.import_playbook: nephelaiio.patroni.patroni


- name: Deploy Barman nodes
  ansible.builtin.import_playbook: nephelaiio.patroni.barman


- name: Manage PostgreSQL databases
  ansible.builtin.import_playbook: nephelaiio.patroni.databases
