---
- name: Set cluster facts
  ansible.builtin.import_playbook: nephelaiio.patroni.facts


- name: Deploy Patroni components
  hosts: "{{ _patroni_cluster_group }}"
  become: true
  vars_files:
    - main.yml
  roles:
    - nephelaiio.patroni.pgdg
    - nephelaiio.patroni.postgresql
  tasks:
    - name: Install patroni
      ansible.builtin.package:
        name: patroni
