---
- name: Set cluster facts
  ansible.builtin.import_playbook: nephelaiio.patroni.facts


- name: Update cluster slaves
  hosts: "_patroni_cluster_slave"
  serial: 1
  tasks:
    - debug:
        msg: updating slaves


- name: Update cluster master
  hosts: "_patroni_cluster_master"
  tasks:
    - debug:
        msg: updating master
