---
name: molecule

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master
    paths:
      - "*"
      - "!README.md"

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - install
          - databases
        image:
          - name: ubuntu2204
            command: /lib/systemd/systemd
          - name: debian12
            command: /lib/systemd/systemd
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      MOLECULE_OUTPUT_DIR: /tmp/logs
    steps:
      - name: Run devbox tests
        uses: pokerops/ansible-utils@master
        with:
          run: devbox run -- make requirements test MOLECULE_SCENARIO=${{ matrix.scenario }} MOLECULE_DOCKER_IMAGE=${{ matrix.image.name }} MOLECULE_DOCKER_COMMAND=${{ matrix.image.command }}

      - name: Upload install logs
        uses: actions/upload-artifact@v4
        with:
          name: install-${{ matrix.scenario }}-${{ matrix.image.name }}.log
          path: |
            /tmp/logs/*
          if-no-files-found: ignore
        if: always()
