---
name: molecule

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  pull_request:
    branches:
      - master

jobs:
  molecule:
    name: molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scenario:
          - name: install
          - name: databases
        image:
          - name: ubuntu2204
            command: /lib/systemd/systemd
          - name: debian12
            command: /lib/systemd/systemd
    steps:
      - name: Check out the codebase
        uses: actions/checkout@v4

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.12.0

      - name: Install requirements
        run: devbox run -- make requirements

      - name: Run molecule tests.
        run: devbox run -- make test
        env:
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image.name }}
          MOLECULE_DOCKER_COMMAND: ${{ matrix.image.command }}
          MOLECULE_SCENARIO: ${{ matrix.scenario.name }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
